import {useState} from 'react';
import {Alert,Box,Button,Card,CardContent,TextField,Typography} from '@mui/material';
import {useAuth} from './authStore';

export default function LoginPage(){
 const login=useAuth(s=>s.login),loading=useAuth(s=>s.loading);const [tenantSlug,setTenantSlug]=useState('demo');const [email,setEmail]=useState('owner@demo.projexa.local');const [password,setPassword]=useState('');const [error,setError]=useState('');
 const submit=async(e:any)=>{e.preventDefault();setError('');try{await login(tenantSlug,email,password);window.location.href='/owner'}catch(err:any){setError(err?.response?.data?.error?.message??err?.response?.data?.message??'Invalid credentials')}};
 return <Box sx={{minHeight:'100vh',display:'grid',placeItems:'center',bgcolor:'#f5f8f7',p:2}}><Card elevation={0} sx={{width:'100%',maxWidth:460,border:'1px solid #e5e7eb',borderRadius:4}}><CardContent sx={{p:{xs:3,sm:4}}}><Box sx={{display:'flex',alignItems:'center',gap:1.5,mb:3}}><Box sx={{width:44,height:44,borderRadius:2.5,bgcolor:'#0f766e',color:'#fff',display:'grid',placeItems:'center',fontWeight:900,fontSize:20}}>P</Box><Box><Typography sx={{fontWeight:900,fontSize:18}}>PROJEXA</Typography><Typography sx={{fontSize:10,color:'#64748b',fontWeight:800,letterSpacing:1.1}}>COACHING OPERATING SYSTEM</Typography></Box></Box><Typography component="h1" sx={{fontSize:28,fontWeight:900}}>Sign in</Typography><Typography sx={{fontSize:13,color:'#64748b',mt:.5,mb:3}}>Access your institute workspace.</Typography><Box component="form" onSubmit={submit} sx={{display:'grid',gap:2}}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Institute slug" value={tenantSlug} onChange={e=>setTenantSlug(e.target.value)} size="small" fullWidth/><TextField label="Email" value={email} onChange={e=>setEmail(e.target.value)} size="small" fullWidth/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} size="small" fullWidth/><Button type="submit" variant="contained" disabled={loading} size="large" sx={{mt:1,borderRadius:2.2,textTransform:'none',fontWeight:800}}>{loading?'Signing in…':'Sign in'}</Button></Box><Typography sx={{fontSize:11,color:'#94a3b8',mt:3}}>Development tenant: demo</Typography></CardContent></Card></Box>
}
