package com.projexa.coaching.automation.controller;
import com.projexa.coaching.automation.service.AutomationExecutionService; import com.projexa.coaching.common.tenant.TenantContextHolder; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/automations") public class AutomationController {private final JdbcTemplate db;private final AutomationExecutionService engine;public AutomationController(JdbcTemplate db,AutomationExecutionService e){this.db=db;this.engine=e;}
 @GetMapping @PreAuthorize("hasAuthority('automation.manage')") public List<Map<String,Object>> list(){return db.queryForList("select * from automation_rules where tenant_id=? order by created_at desc",TenantContextHolder.getRequired());}
 @PostMapping @PreAuthorize("hasAuthority('automation.manage')") public Map<String,Object> create(@RequestBody CreateRule req){
  if(req==null||req.name()==null||req.name().isBlank()||req.triggerEvent()==null||req.triggerEvent().isBlank()) throw new IllegalArgumentException("Automation name and trigger event are required");
  if(req.cooldownSeconds()<0||req.cooldownSeconds()>86400) throw new IllegalArgumentException("Cooldown must be between 0 and 86400 seconds");
  if(req.maxDepth()<0||req.maxDepth()>20) throw new IllegalArgumentException("Max depth must be between 0 and 20");
  List<Condition> conditions=req.conditions()==null?List.of():req.conditions(); List<Action> actions=req.actions()==null?List.of():req.actions();
  UUID t=TenantContextHolder.getRequired(),id=UUID.randomUUID();db.update("insert into automation_rules(id,tenant_id,name,trigger_event,active,cooldown_seconds,max_depth) values(?,?,?,?,?,?,?)",id,t,req.name(),req.triggerEvent(),false,req.cooldownSeconds(),req.maxDepth());for(Condition c:conditions)db.update("insert into automation_conditions(id,rule_id,field_name,operator,comparison_value) values(?,?,?,?,?)",UUID.randomUUID(),id,c.fieldName(),c.operator(),c.value());for(int i=0;i<actions.size();i++){Action a=actions.get(i);db.update("insert into automation_actions(id,rule_id,action_type,action_config,action_order) values(?,?,?,?,?)",UUID.randomUUID(),id,a.type(),a.config(),i);}return Map.of("id",id,"active",false);}
 @PostMapping("/{id}/activate") @PreAuthorize("hasAuthority('automation.manage')") public Map<String,Object> activate(@PathVariable UUID id,@RequestParam boolean active){int n=db.update("update automation_rules set active=?,updated_at=now() where id=? and tenant_id=?",active,id,TenantContextHolder.getRequired());return Map.of("updated",n>0,"active",active);}
 @PostMapping("/{id}/test") @PreAuthorize("hasAuthority('automation.manage')") public Map<String,Object> test(@PathVariable UUID id,@RequestBody Map<String,Object> payload){UUID t=TenantContextHolder.getRequired();String event=db.queryForObject("select trigger_event from automation_rules where id=? and tenant_id=?",String.class,id,t);engine.executeEvent(t,event,"TEST-"+UUID.randomUUID(),payload);return Map.of("executed",true,"mode","TEST");}
 public record CreateRule(String name,String triggerEvent,int cooldownSeconds,int maxDepth,List<Condition> conditions,List<Action> actions){} public record Condition(String fieldName,String operator,String value){} public record Action(String type,String config){}
}
