package com.projexa.coaching.auth.service;
import com.projexa.coaching.auth.dto.*; import com.projexa.coaching.auth.security.JwtService; import com.projexa.coaching.common.exceptions.ApiException; import com.projexa.coaching.tenancy.entity.Tenant; import com.projexa.coaching.tenancy.repository.TenantRepository; import com.projexa.coaching.users.entity.*; import com.projexa.coaching.users.repository.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.security.SecureRandom; import java.time.*; import java.util.*; import java.util.stream.Collectors;
@Service public class AuthService { private final TenantRepository tenants; private final UserRepository users; private final RefreshTokenRepository refreshTokens; private final PasswordEncoder encoder; private final JwtService jwt; private final SecureRandom random=new SecureRandom(); public AuthService(TenantRepository t,UserRepository u,RefreshTokenRepository r,PasswordEncoder e,JwtService j){tenants=t;users=u;refreshTokens=r;encoder=e;jwt=j;}
@Transactional public LoginResponse login(LoginRequest req){Tenant tenant=tenants.findBySlugAndStatus(req.tenantSlug().toLowerCase(),"ACTIVE").orElseThrow(()->new ApiException("INVALID_CREDENTIALS","Invalid institute or credentials")); User u=users.findByTenantIdAndEmail(tenant.getId(),req.email().toLowerCase()).orElseThrow(()->new ApiException("INVALID_CREDENTIALS","Invalid institute or credentials")); if(!"ACTIVE".equals(u.getStatus())||!encoder.matches(req.password(),u.getPasswordHash()))throw new ApiException("INVALID_CREDENTIALS","Invalid institute or credentials"); return issue(u,tenant);}
@Transactional public LoginResponse refresh(String raw){String hash=hash(raw); RefreshToken rt=refreshTokens.findByTokenHashAndRevokedAtIsNull(hash).filter(x->x.getExpiresAt().isAfter(LocalDateTime.now())).orElseThrow(()->new ApiException("INVALID_REFRESH_TOKEN","Refresh token is invalid or expired")); rt.setRevokedAt(LocalDateTime.now());rt.setLastUsedAt(LocalDateTime.now()); User u=users.findById(rt.getUserId()).orElseThrow(()->new ApiException("USER_NOT_FOUND","User not found")); Tenant t=tenants.findByIdAndStatus(u.getTenantId(),"ACTIVE").orElseThrow(()->new ApiException("TENANT_INACTIVE","Institute is inactive")); return issue(u,t);}
@Transactional public void logout(String raw){String h=hash(raw); refreshTokens.findAll().stream().filter(x->x.getTokenHash().equals(h)&&x.getRevokedAt()==null).forEach(x->{x.setRevokedAt(LocalDateTime.now());x.setLastUsedAt(LocalDateTime.now());});}
private LoginResponse issue(User u,Tenant t){Set<String> roles=u.getRoles().stream().map(Role::getCode).collect(Collectors.toSet());Set<String> perms=u.getRoles().stream().flatMap(r->r.getPermissions().stream()).map(Permission::getCode).collect(Collectors.toSet());Set<String> authorities=new HashSet<>(perms);roles.forEach(r->authorities.add("ROLE_"+r));String access=jwt.generate(u.getId(),t.getId(),u.getEmail(),authorities);String refresh=generateRefresh();RefreshToken rt=new RefreshToken();rt.setUserId(u.getId());rt.setTokenHash(hash(refresh));rt.setExpiresAt(LocalDateTime.now().plusDays(30));refreshTokens.save(rt);return new LoginResponse(access,refresh,jwt.expiresIn(),u.getId(),t.getId(),t.getName(),u.getFirstName(),u.getLastName(),roles,perms);}
private String generateRefresh(){byte[] b=new byte[48];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String value){try{var md=java.security.MessageDigest.getInstance("SHA-256");return HexFormat.of().formatHex(md.digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
