import {useEffect,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,InputLabel,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {AddRounded,TrendingUpRounded} from '@mui/icons-material';
import {api} from '../services';

const stages=['ENQUIRY','COUNSELLING','DEMO','FOLLOW_UP','ADMITTED','LOST'];
function unwrap(r:any){return r?.data?.data??r?.data??[]}
function err(e:any,f:string){return e?.response?.data?.message||e?.response?.data?.error?.message||f}

export default function AdmissionsPage(){
 const [leads,setLeads]=useState<any[]>([]),[funnel,setFunnel]=useState<any>(),[error,setError]=useState(''),[open,setOpen]=useState(false);
 const [search,setSearch]=useState(''),[stage,setStage]=useState('ALL'),[form,setForm]=useState<any>({name:'',phone:'',email:'',source:'',stage:'ENQUIRY',lostReason:''});
 async function load(){try{setError('');const qs=new URLSearchParams();if(search.trim())qs.set('search',search.trim());if(stage!=='ALL')qs.set('stage',stage);const [l,f]=await Promise.all([api.get('/admissions/leads?'+qs),api.get('/admissions/funnel')]);setLeads(unwrap(l));setFunnel(unwrap(f))}catch(e:any){setError(err(e,'Unable to load admissions CRM'))}}
 useEffect(()=>{load()},[stage]);useEffect(()=>{const x=setTimeout(load,350);return()=>clearTimeout(x)},[search]);
 async function save(){try{await api.post('/admissions/leads',form);setOpen(false);setForm({name:'',phone:'',email:'',source:'',stage:'ENQUIRY',lostReason:''});await load()}catch(e:any){setError(err(e,'Unable to create lead'))}}
 async function move(id:string,next:string){try{await api.post('/admissions/leads/'+id+'/stage',{stage:next,lostReason:next==='LOST'?'Not interested / unavailable':''});await load()}catch(e:any){setError(err(e,'Unable to move lead'))}}
 return <Box>
  <Stack direction={{xs:'column',md:'row'}} spacing={2} sx={{mb:2,justifyContent:'space-between',alignItems:{md:'center'}}}><Typography sx={{fontSize:13,color:'#64748b'}}>Admissions CRM: enquiry → counselling → demo → follow-up → admission, with activity and follow-up history.</Typography><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>setOpen(true)} sx={{textTransform:'none'}}>Add lead</Button></Stack>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
  {funnel&&<><Stack direction="row" spacing={1} sx={{mb:2,alignItems:'center'}}><TrendingUpRounded color="primary"/><Typography sx={{fontWeight:900}}>Admission funnel</Typography></Stack><Box sx={{display:'grid',gridTemplateColumns:{xs:'repeat(2,1fr)',md:'repeat(6,1fr)'},gap:1.5,mb:2}}>{stages.map(s=><Card key={s} variant="outlined" sx={{borderRadius:3}}><CardContent><Typography sx={{fontSize:10,color:'#64748b'}}>{s.replace('_',' ')}</Typography><Typography sx={{fontSize:24,fontWeight:900}}>{(funnel.stages||[]).find((x:any)=>x.stage===s)?.count||0}</Typography></CardContent></Card>)}</Box></>}
  <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction={{xs:'column',sm:'row'}} spacing={1.5} sx={{mb:2}}><TextField size="small" placeholder="Search name, phone or email" value={search} onChange={e=>setSearch(e.target.value)} sx={{minWidth:{sm:300}}}/><FormControl size="small" sx={{minWidth:180}}><InputLabel>Stage</InputLabel><Select label="Stage" value={stage} onChange={e=>setStage(e.target.value)}><MenuItem value="ALL">All stages</MenuItem>{stages.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl></Stack>
   {!leads.length?<Typography sx={{py:5,textAlign:'center',color:'#64748b'}}>No leads found.</Typography>:<Table size="small"><TableHead><TableRow><TableCell>Lead</TableCell><TableCell>Source</TableCell><TableCell>Stage</TableCell><TableCell>Next follow-up</TableCell><TableCell align="right">Move</TableCell></TableRow></TableHead><TableBody>{leads.map(l=><TableRow key={l.id} hover><TableCell><Typography sx={{fontWeight:800}}>{l.name}</Typography><Typography sx={{fontSize:11,color:'#64748b'}}>{l.phone||l.email||'No contact details'}</Typography></TableCell><TableCell>{l.source||'—'}</TableCell><TableCell><Chip size="small" label={l.stage}/></TableCell><TableCell>{l.next_follow_up?new Date(l.next_follow_up).toLocaleString():'—'}</TableCell><TableCell align="right"><Select size="small" value="" displayEmpty onChange={e=>move(l.id,e.target.value)} sx={{minWidth:140}}><MenuItem value="" disabled>Move stage</MenuItem>{stages.filter(s=>s!==l.stage).map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></TableCell></TableRow>)}</TableBody></Table>}
  </CardContent></Card>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle sx={{fontWeight:900}}>Add admission lead</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Name" size="small" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField label="Phone" size="small" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><TextField label="Email" size="small" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField label="Source" size="small" placeholder="Instagram, Referral, Walk-in..." value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.name.trim()} onClick={save}>Create lead</Button></DialogActions></Dialog>
 </Box>
}
