import {useEffect,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,IconButton,InputLabel,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Tooltip,Typography} from '@mui/material';
import {AddRounded,DeleteOutlineRounded,EditRounded,QuizRounded,LibraryAddRounded} from '@mui/icons-material';
import {api} from '../services';

type Exam={id:string;academic_year_id:string;name:string;exam_type:string;starts_at?:string;ends_at?:string;status:string;academic_year:string;subject_count:number;question_count:number;attempt_count:number};
type R={id:string;name:string;code?:string};
function unwrap(r:any){return r?.data?.data??r?.data??[]}
function err(e:any,f:string){return e?.response?.data?.message||e?.response?.data?.error?.message||f}

export default function ExamsPage(){
 const [items,setItems]=useState<Exam[]>([]),[years,setYears]=useState<R[]>([]),[subjects,setSubjects]=useState<R[]>([]),[questions,setQuestions]=useState<any[]>([]);
 const [error,setError]=useState(''),[open,setOpen]=useState(false),[subjectOpen,setSubjectOpen]=useState(false),[questionOpen,setQuestionOpen]=useState(false),[editing,setEditing]=useState<Exam|null>(null),[selected,setSelected]=useState<Exam|null>(null);
 const [form,setForm]=useState<any>({academicYearId:'',name:'',examType:'UNIT_TEST',startsAt:'',endsAt:'',status:'DRAFT'});
 const [subjectForm,setSubjectForm]=useState<any>({subjectId:'',maxMarks:'100',passMarks:'33',negativeMarking:'0'}),[questionIds,setQuestionIds]=useState<string[]>([]);

 async function load(){try{setError('');const [e,r]=await Promise.all([api.get('/exams'),api.get('/exams/resources')]);setItems(unwrap(e));const x=unwrap(r);setYears(x.academicYears??[]);setSubjects(x.subjects??[]);setQuestions(x.questions??[])}catch(e:any){setError(err(e,'Unable to load exams'))}}
 useEffect(()=>{load()},[]);
 function edit(x?:Exam){setEditing(x??null);setForm(x?{academicYearId:x.academic_year_id,name:x.name,examType:x.exam_type,startsAt:x.starts_at?String(x.starts_at).slice(0,16):'',endsAt:x.ends_at?String(x.ends_at).slice(0,16):'',status:x.status}:{academicYearId:years.find((y:any)=>y.is_current)?.id||years[0]?.id||'',name:'',examType:'UNIT_TEST',startsAt:'',endsAt:'',status:'DRAFT'});setOpen(true)}
 async function save(){try{const p={...form,startsAt:form.startsAt||null,endsAt:form.endsAt||null};if(editing)await api.put('/exams/'+editing.id,p);else await api.post('/exams',p);setOpen(false);await load()}catch(e:any){setError(err(e,'Unable to save exam'))}}
 async function remove(x:Exam){if(!window.confirm('Archive this exam?'))return;try{await api.delete('/exams/'+x.id);await load()}catch(e:any){setError(err(e,'Unable to archive exam'))}}
 async function openSubjects(x:Exam){setSelected(x);setSubjectOpen(true)}
 async function saveSubject(){if(!selected)return;try{await api.post('/exams/'+selected.id+'/subjects',{subjectId:subjectForm.subjectId,maxMarks:Number(subjectForm.maxMarks),passMarks:subjectForm.passMarks===''?null:Number(subjectForm.passMarks),negativeMarking:Number(subjectForm.negativeMarking||0)});setSubjectForm({subjectId:'',maxMarks:'100',passMarks:'33',negativeMarking:'0'});await load()}catch(e:any){setError(err(e,'Unable to configure subject'))}}
 async function openQuestions(x:Exam){try{setSelected(x);const r=await api.get('/exams/'+x.id+'/questions');setQuestionIds(unwrap(r).map((q:any)=>q.id));setQuestionOpen(true)}catch(e:any){setError(err(e,'Unable to load exam questions'))}}
 async function saveQuestions(){if(!selected)return;try{await api.post('/exams/'+selected.id+'/questions',{questionIds});setQuestionOpen(false);await load()}catch(e:any){setError(err(e,'Unable to save exam questions'))}}

 return <Box>
  <Stack direction={{xs:'column',md:'row'}} spacing={2} sx={{mb:2,justifyContent:'space-between',alignItems:{xs:'stretch',md:'center'}}}><Typography sx={{fontSize:13,color:'#64748b'}}>Build traditional, objective and online assessments from one configurable exam engine.</Typography><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>edit()} sx={{textTransform:'none',fontWeight:800}}>Create exam</Button></Stack>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
  {!items.length?<Card variant="outlined" sx={{borderRadius:3}}><CardContent sx={{py:6,textAlign:'center'}}><QuizRounded sx={{fontSize:44,color:'#0f766e'}}/><Typography sx={{fontWeight:900,fontSize:18,mt:1}}>No exams yet</Typography><Typography sx={{color:'#64748b',mt:.5}}>Create an exam, configure subjects and attach questions.</Typography></CardContent></Card>:
  <Card variant="outlined" sx={{borderRadius:3}}><Table size="small"><TableHead><TableRow><TableCell>Exam</TableCell><TableCell>Status</TableCell><TableCell>Subjects</TableCell><TableCell>Questions</TableCell><TableCell>Attempts</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{items.map(x=><TableRow key={x.id} hover><TableCell><Typography sx={{fontWeight:800}}>{x.name}</Typography><Typography sx={{fontSize:11,color:'#64748b'}}>{x.exam_type} · {x.academic_year}</Typography></TableCell><TableCell><Chip size="small" label={x.status}/></TableCell><TableCell>{x.subject_count}</TableCell><TableCell>{x.question_count}</TableCell><TableCell>{x.attempt_count}</TableCell><TableCell align="right"><Tooltip title="Subjects"><IconButton size="small" onClick={()=>openSubjects(x)}><LibraryAddRounded fontSize="small"/></IconButton></Tooltip><Tooltip title="Questions"><IconButton size="small" onClick={()=>openQuestions(x)}><QuizRounded fontSize="small"/></IconButton></Tooltip><Tooltip title="Edit"><IconButton size="small" onClick={()=>edit(x)}><EditRounded fontSize="small"/></IconButton></Tooltip><Tooltip title="Archive"><IconButton size="small" onClick={()=>remove(x)}><DeleteOutlineRounded fontSize="small"/></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></Card>}
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle sx={{fontWeight:900}}>{editing?'Edit exam':'Create exam'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>
   <FormControl fullWidth size="small"><InputLabel>Academic year</InputLabel><Select label="Academic year" value={form.academicYearId} onChange={e=>setForm({...form,academicYearId:e.target.value})}>{years.map(y=><MenuItem key={y.id} value={y.id}>{y.name}{y.is_current?' · Current':''}</MenuItem>)}</Select></FormControl>
   <TextField size="small" label="Exam name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><TextField size="small" label="Exam type" value={form.examType} onChange={e=>setForm({...form,examType:e.target.value})}/>
   <Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:2}}><TextField size="small" type="datetime-local" label="Starts" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField size="small" type="datetime-local" label="Ends" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></Box>
   <FormControl fullWidth size="small"><InputLabel>Status</InputLabel><Select label="Status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['DRAFT','SCHEDULED','LIVE','COMPLETED','ARCHIVED'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</Select></FormControl>
  </Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.academicYearId||!form.name.trim()} onClick={save}>Save exam</Button></DialogActions></Dialog>

  <Dialog open={subjectOpen} onClose={()=>setSubjectOpen(false)} fullWidth maxWidth="md"><DialogTitle sx={{fontWeight:900}}>Exam subjects · {selected?.name}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'2fr 1fr 1fr 1fr auto'},gap:1.5,alignItems:'center'}}><FormControl size="small"><InputLabel>Subject</InputLabel><Select label="Subject" value={subjectForm.subjectId} onChange={e=>setSubjectForm({...subjectForm,subjectId:e.target.value})}>{subjects.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select></FormControl><TextField size="small" label="Max" value={subjectForm.maxMarks} onChange={e=>setSubjectForm({...subjectForm,maxMarks:e.target.value})}/><TextField size="small" label="Pass" value={subjectForm.passMarks} onChange={e=>setSubjectForm({...subjectForm,passMarks:e.target.value})}/><TextField size="small" label="Negative" value={subjectForm.negativeMarking} onChange={e=>setSubjectForm({...subjectForm,negativeMarking:e.target.value})}/><Button variant="contained" disabled={!subjectForm.subjectId} onClick={saveSubject}>Add</Button></Box><Typography sx={{fontSize:12,color:'#64748b'}}>Adding the same subject updates its marks configuration.</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setSubjectOpen(false)}>Close</Button></DialogActions></Dialog>

  <Dialog open={questionOpen} onClose={()=>setQuestionOpen(false)} fullWidth maxWidth="md"><DialogTitle sx={{fontWeight:900}}>Question selection · {selected?.name}</DialogTitle><DialogContent><Stack spacing={1} sx={{pt:1}}>{questions.map(q=><Box key={q.id} sx={{p:1.2,border:'1px solid #e5e7eb',borderRadius:2,display:'flex',gap:1,alignItems:'center'}}><input type="checkbox" checked={questionIds.includes(q.id)} onChange={e=>setQuestionIds(v=>e.target.checked?[...v,q.id]:v.filter(id=>id!==q.id))}/><Box sx={{flex:1}}><Typography sx={{fontSize:13,fontWeight:700}}>{q.text}</Typography><Typography sx={{fontSize:11,color:'#64748b'}}>{q.question_type} · {q.difficulty||'Unspecified'} · {q.marks} marks</Typography></Box></Box>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setQuestionOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveQuestions}>Save {questionIds.length} questions</Button></DialogActions></Dialog>
 </Box>
}
