import {useEffect,useMemo,useState} from 'react';
import {api} from '../services';
import {Alert,Box,Button,Card,CardContent,Chip,CircularProgress,InputAdornment,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {SearchRounded,RefreshRounded,FilterListRounded,ArrowForwardRounded} from '@mui/icons-material';
export default function ModuleDataPage({title,endpoint,columns}:{title:string;endpoint:string;columns:string[]}){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState('');
 const load=()=>{setLoading(true);setError('');api.get(endpoint).then(r=>{const d=r.data?.data??r.data;setRows(Array.isArray(d)?d:(d?.data??[]));}).catch(e=>setError(e.response?.data?.error?.message??e.response?.data?.message??'Unable to load data')).finally(()=>setLoading(false));};
 useEffect(load,[endpoint]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 return <Card elevation={0} sx={{border:'1px solid #e5e7eb',borderRadius:3}}><CardContent sx={{p:{xs:1.5,md:2.5}}}>
  <Stack direction={{xs:'column',sm:'row'}} gap={1.5} justifyContent="space-between" mb={2}><TextField value={query} onChange={e=>setQuery(e.target.value)} size="small" placeholder={`Search ${title.toLowerCase()}...`} sx={{maxWidth:360}} InputProps={{startAdornment:<InputAdornment position="start"><SearchRounded fontSize="small"/></InputAdornment>}}/><Stack direction="row" gap={1}><Button size="small" variant="outlined" startIcon={<FilterListRounded/>} sx={{textTransform:'none'}}>Filters</Button><Button size="small" variant="outlined" startIcon={<RefreshRounded/>} onClick={load} sx={{textTransform:'none'}}>Refresh</Button></Stack></Stack>
  {loading?<Box py={8} textAlign="center"><CircularProgress size={28}/><Typography fontSize={12} color="text.secondary" mt={1}>Loading live data…</Typography></Box>:error?<Alert severity="error">{error}</Alert>:filtered.length===0?<Box py={8} textAlign="center"><Typography fontWeight={800}>No records found</Typography><Typography fontSize={12} color="text.secondary">Try changing your search or create a new record.</Typography></Box>:<Box sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{columns.map(c=><TableCell key={c} sx={{fontSize:11,fontWeight:900,color:'#64748b',textTransform:'uppercase',whiteSpace:'nowrap'}}>{c.replaceAll('_',' ')}</TableCell>)}<TableCell/></TableRow></TableHead><TableBody>{filtered.map((r,i)=><TableRow hover key={r.id??i} sx={{'& td':{borderColor:'#f1f5f9'}}}>{columns.map(c=><TableCell key={c} sx={{fontSize:13,whiteSpace:'nowrap'}}>{c==='status'||c==='stage'?<Chip size="small" label={String(r[c]??'—')} variant="outlined"/>:String(r[c]??'—')}</TableCell>)}<TableCell align="right"><Button size="small" endIcon={<ArrowForwardRounded/>} sx={{textTransform:'none'}}>View</Button></TableCell></TableRow>)}</TableBody></Table></Box>}
  {!loading&&!error&&<Stack direction="row" justifyContent="space-between" mt={2}><Typography fontSize={11} color="text.secondary">Showing {filtered.length} of {rows.length} records</Typography><Typography fontSize={11} color="text.secondary">Tenant-scoped data</Typography></Stack>}
 </CardContent></Card>
}
