// @ts-nocheck
import {useEffect,useMemo,useState} from 'react';
import {api} from '../services';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,IconButton,InputAdornment,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {AddRounded,DeleteOutlineRounded,EditRounded,RefreshRounded,SearchRounded,PaymentsRounded,EventAvailableRounded,PeopleRounded,TrendingUpRounded} from '@mui/icons-material';

const unwrap=(r:any)=>r?.data?.data??r?.data;
const err=(e:any)=>{const status=e?.response?.status; const body=e?.response?.data; const message=body?.error?.message??body?.message??body?.error??(typeof body==='string'?body:''); return [(status ? 'HTTP '+status : ''),message].filter(Boolean).join(': ')||e?.message||'Request failed';};

function useList(endpoint:string){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get(endpoint);const d=unwrap(r);setRows(Array.isArray(d)?d:(d?.data??[]));}catch(e){setError(err(e));}finally{setLoading(false);}};
 useEffect(()=>{load();},[endpoint]); return {rows,loading,error,load,setRows};
}
function Busy({loading,error}:{loading:boolean;error:string}){if(loading)return <Typography sx={{color:'text.secondary',py:4,textAlign:'center'}}>Loading live data…</Typography>;if(error)return <Alert severity="error">{error}</Alert>;return null;}
function Stat({label,value,caption,icon:Icon}:{label:string;value:any;caption?:string;icon:any}){return <Card elevation={0} sx={{border:'1px solid #e5e7eb',borderRadius:3}}><CardContent><Icon sx={{fontSize:20,color:'#0f766e'}}/><Typography sx={{fontSize:12,color:'text.secondary',mt:1}}>{label}</Typography><Typography sx={{fontSize:26,fontWeight:900}}>{value}</Typography>{caption&&<Typography sx={{fontSize:11,color:'text.secondary'}}>{caption}</Typography>}</CardContent></Card>}

export function LiveDashboard(){
 const [data,setData]=useState<any>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{setData(unwrap(await api.get('/dashboard/summary'))||{});setError('')}catch(e){setError(err(e))}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 if(error)return <Alert severity="error">{error}</Alert>;
 return <Stack spacing={2.5}><Stack direction="row" justifyContent="flex-end"><Button variant="outlined" startIcon={<RefreshRounded/>} onClick={load}>Refresh</Button></Stack>
 {loading?<Card><CardContent><Typography sx={{py:8,textAlign:'center'}}>Loading institute command center…</Typography></CardContent></Card>:<>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',lg:'repeat(4,1fr)'},gap:2}}><Stat label="Active Students" value={data.students??0} caption="Current tenant" icon={PeopleRounded}/><Stat label="Today's Attendance" value={`${data.attendance??0}%`} caption={`${data.todaySessions??0} sessions`} icon={EventAvailableRounded}/><Stat label="Collected" value={money(data.collected)} caption="All recorded invoices" icon={PaymentsRounded}/><Stat label="Outstanding" value={money(data.outstanding)} caption={`${data.overdue??0} overdue invoices`} icon={TrendingUpRounded}/></Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.3fr .7fr'},gap:2}}><Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Typography sx={{fontWeight:900}}>Recent payments</Typography><Typography sx={{fontSize:12,color:'text.secondary',mb:2}}>Live payment ledger</Typography><Table size="small"><TableHead><TableRow><TableCell>Student</TableCell><TableCell>Invoice</TableCell><TableCell align="right">Amount</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{(data.recentPayments||[]).map((p:any)=><TableRow key={p.id}><TableCell>{p.first_name} {p.last_name||''}</TableCell><TableCell>{p.invoice_number}</TableCell><TableCell align="right">{money(p.amount)}</TableCell><TableCell><Chip size="small" label="SUCCESS" color="success" variant="outlined"/></TableCell></TableRow>)}{!(data.recentPayments||[]).length&&<TableRow><TableCell colSpan={4}>No payments recorded yet.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
 <Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Typography fontWeight={900}>Institute health</Typography><Stack spacing={1.2} mt={2}>{[['Active batches',data.batches],['Open alerts',data.alerts],['Overdue invoices',data.overdue]].map(([a,b])=><Stack key={a as string} direction="row" justifyContent="space-between" p={1.3} sx={{bgcolor:'#f8fafc',borderRadius:2}}><Typography sx={{fontSize:13}}>{a as string}</Typography><Typography sx={{fontWeight:900}}>{b as any}</Typography></Stack>)}</Stack></CardContent></Card></Box></>}</Stack>
}

const money=(n:any)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

export function LiveStudentsPage(){
 const {rows,loading,error,load}=useList('/students/operational'); const [q,setQ]=useState(''); const [open,setOpen]=useState(false);const [edit,setEdit]=useState<any>(null); const [enroll,setEnroll]=useState<any>(null);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <Stack spacing={2.5}><Stack direction={{xs:'column',sm:'row'}} gap={1.5}><TextField size="small" fullWidth placeholder="Search name, admission number, phone…" value={q} onChange={e=>setQ(e.target.value)} slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchRounded fontSize="small"/></InputAdornment>}}}/><Button variant="outlined" startIcon={<RefreshRounded/>} onClick={load}>Refresh</Button><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>{setEdit(null);setOpen(true)}}>Add student</Button></Stack><Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent sx={{p:0,overflow:'auto'}}><Busy loading={loading} error={error}/>{!loading&&!error&&<Table><TableHead><TableRow>{['Admission','Student','Class / Batch','Phone','Email','Status',''].map(x=><TableCell key={x} sx={{fontWeight:900,fontSize:11}}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{filtered.map(r=><TableRow hover key={r.id}><TableCell>{r.admissionNumber}</TableCell><TableCell><Typography sx={{fontWeight:800}}>{r.firstName} {r.lastName||''}</Typography></TableCell><TableCell>{r.className?`${r.className} • ${r.batchName||'No batch'}`:'Not enrolled'}</TableCell><TableCell>{r.phone||'—'}</TableCell><TableCell>{r.email||'—'}</TableCell><TableCell><Chip size="small" label={r.status} color={r.status==='ACTIVE'?'success':'default'} variant="outlined"/></TableCell><TableCell align="right"><Button size="small" onClick={()=>setEnroll(r)}>Enroll</Button><IconButton onClick={()=>{setEdit(r);setOpen(true)}}><EditRounded fontSize="small"/></IconButton><IconButton color="error" onClick={async()=>{if(confirm('Archive this student?')){await api.delete(`/students/${r.id}`);load()}}}><DeleteOutlineRounded fontSize="small"/></IconButton></TableCell></TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={7}><Typography sx={{py:5,textAlign:'center',color:'text.secondary'}}>No students found.</Typography></TableCell></TableRow>}</TableBody></Table>}</CardContent></Card><StudentDialog open={open} initial={edit} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/><EnrollmentDialog open={!!enroll} student={enroll} onClose={()=>setEnroll(null)} onSaved={()=>{setEnroll(null);load()}}/></Stack>
}

function StudentDialog({open,initial,onClose,onSaved}:{open:boolean;initial:any;onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState<any>({admissionNumber:'',firstName:'',lastName:'',phone:'',email:'',dateOfBirth:'',gender:'',address:'',status:'ACTIVE'});const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{setForm(initial?{...initial,dateOfBirth:initial.dateOfBirth||''}:{admissionNumber:'',firstName:'',lastName:'',phone:'',email:'',dateOfBirth:'',gender:'',address:'',status:'ACTIVE'});setError('')},[initial,open]);
 const save=async()=>{setSaving(true);setError('');try{if(initial)await api.put(`/students/${initial.id}`,form);else await api.post('/students',form);onSaved()}catch(e){setError(err(e))}finally{setSaving(false)}};const f=(k:string)=>(e:any)=>setForm((x:any)=>({...x,[k]:e.target.value}));
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>{initial?'Edit student':'Add student'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2}}>{[['admissionNumber','Admission number'],['firstName','First name'],['lastName','Last name'],['phone','Phone'],['email','Email'],['dateOfBirth','Date of birth'],['gender','Gender'],['address','Address']].map(([k,l])=><TextField key={k} label={l} value={form[k]||''} onChange={f(k)} type={k==='dateOfBirth'?'date':'text'} slotProps={k==='dateOfBirth'?{inputLabel:{shrink:true}}:undefined}/>)}</Box><Select value={form.status} onChange={f('status')}><MenuItem value="ACTIVE">Active</MenuItem><MenuItem value="INACTIVE">Inactive</MenuItem><MenuItem value="WITHDRAWN">Withdrawn</MenuItem></Select></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving…':'Save student'}</Button></DialogActions></Dialog>
}

function EnrollmentDialog({open,student,onClose,onSaved}:{open:boolean;student:any;onClose:()=>void;onSaved:()=>void}){const {rows:years}=useList('/academic-years');const {rows:classes}=useList('/classes');const {rows:streams}=useList('/streams');const {rows:batches}=useList('/batches');const [f,setF]=useState<any>({academicYearId:'',classId:'',streamId:'',batchId:''});const [error,setError]=useState('');useEffect(()=>{setF({academicYearId:years.find((x:any)=>x.isCurrent)?.id||years[0]?.id||'',classId:student?.classId||'',streamId:student?.streamId||'',batchId:student?.batchId||''})},[open,student,years]);const save=async()=>{setError('');if(!f.academicYearId||!f.classId||!f.batchId){setError('Academic year, class and batch are required.');return;}try{await api.post(`/students/${student.id}/enrollment`,{...f,streamId:f.streamId||null});onSaved()}catch(e){setError(err(e))}};return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Assign academic enrollment</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Select value={f.academicYearId} displayEmpty onChange={e=>setF((x:any)=>({...x,academicYearId:e.target.value}))}>{years.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select><Select value={f.classId} displayEmpty onChange={e=>setF((x:any)=>({...x,classId:e.target.value}))}><MenuItem value="">Select class</MenuItem>{classes.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select><Select value={f.streamId} displayEmpty onChange={e=>setF((x:any)=>({...x,streamId:e.target.value}))}><MenuItem value="">No stream</MenuItem>{streams.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select><Select value={f.batchId} displayEmpty onChange={e=>setF((x:any)=>({...x,batchId:e.target.value}))}><MenuItem value="">Select batch</MenuItem>{batches.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Save enrollment</Button></DialogActions></Dialog>}

export function LiveStudentProfile({id}:{id:string}){
 const [student,setStudent]=useState<any>(null),[invoices,setInvoices]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const [s,f]=await Promise.all([api.get(`/students/${id}`),api.get('/finance/invoices',{params:{studentId:id}})]);setStudent(unwrap(s));setInvoices(unwrap(f)||[])}finally{setLoading(false)}})()},[id]);
 if(loading)return <Typography>Loading student…</Typography>; if(!student)return <Alert severity="error">Student not found.</Alert>;
 return <Stack spacing={2.5}><Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Typography sx={{fontSize:12,color:'text.secondary'}}>Student record</Typography><Typography variant="h5" sx={{fontWeight:900}}>{student.firstName} {student.lastName||''}</Typography><Typography color="text.secondary">{student.admissionNumber} • {student.phone||'No phone'} • {student.email||'No email'}</Typography></CardContent></Card><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(3,1fr)'},gap:2}}><Stat label="Status" value={student.status} icon={PeopleRounded}/><Stat label="Phone" value={student.phone||'—'} icon={PeopleRounded}/><Stat label="Invoices" value={invoices.length} icon={PaymentsRounded}/></Box><Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Typography sx={{fontWeight:900,mb:1.5}}>Fee ledger</Typography><Table size="small"><TableHead><TableRow><TableCell>Invoice</TableCell><TableCell>Due</TableCell><TableCell>Amount</TableCell><TableCell>Paid</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{invoices.map(i=><TableRow key={i.id}><TableCell>{i.invoice_number}</TableCell><TableCell>{i.due_date}</TableCell><TableCell>{money(i.amount)}</TableCell><TableCell>{money(i.paid_amount)}</TableCell><TableCell><Chip size="small" label={i.status} variant="outlined"/></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></Stack>
}

export function LiveAcademicsPage(){
 const resources=[['Academic years','/academic-years',['name','startDate','endDate','isCurrent']],['Classes','/classes',['name','displayOrder','active']],['Streams','/streams',['name','code','active']],['Subjects','/subjects',['name','code','active']],['Batches','/batches',['name','code','capacity','status']]] as const;
 const [tab,setTab]=useState(0); const [refresh,setRefresh]=useState(0);
 return <Stack spacing={2.5}><Box sx={{display:'flex',gap:1,overflow:'auto'}}>{resources.map((r,i)=><Button key={r[0]} variant={tab===i?'contained':'outlined'} onClick={()=>setTab(i)}>{r[0]}</Button>)}</Box><AcademicResource key={refresh} title={resources[tab][0]} endpoint={resources[tab][1]} fields={[...resources[tab][2]]} onChanged={()=>setRefresh(x=>x+1)}/></Stack>
}
function AcademicResource({title,endpoint,fields,onChanged}:{title:string;endpoint:string;fields:string[];onChanged:()=>void}){
 const {rows,loading,error,load}=useList(endpoint);const [open,setOpen]=useState(false);const [edit,setEdit]=useState<any>(null);
 return <Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Stack direction="row" justifyContent="space-between" mb={2}><Box><Typography fontWeight={900}>{title}</Typography><Typography fontSize={12} color="text.secondary">{rows.length} records in this tenant</Typography></Box><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>{setEdit(null);setOpen(true)}}>Add</Button></Stack><Busy loading={loading} error={error}/>{!loading&&!error&&<Table size="small"><TableHead><TableRow>{fields.map(f=><TableCell key={f} sx={{fontWeight:900,fontSize:11}}>{f}</TableCell>)}<TableCell/></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.id}>{fields.map(f=><TableCell key={f}>{String(r[f]??'—')}</TableCell>)}<TableCell align="right"><IconButton onClick={()=>{setEdit(r);setOpen(true)}}><EditRounded fontSize="small"/></IconButton><IconButton color="error" onClick={async()=>{if(confirm('Delete this record?')){await api.delete(`${endpoint}/${r.id}`);load();onChanged()}}}><DeleteOutlineRounded fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>}{endpoint==='/batches'
        ? <BatchDialog open={open} initial={edit} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load();onChanged()}}/>
        : <AcademicDialog open={open} initial={edit} endpoint={endpoint} fields={fields} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load();onChanged()}}/>}</CardContent></Card>
}
function AcademicDialog({open,initial,endpoint,fields,onClose,onSaved}:{open:boolean;initial:any;endpoint:string;fields:string[];onClose:()=>void;onSaved:()=>void}){
 const [form,setForm]=useState<any>({});const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const x:any={};fields.forEach(f=>x[f]=initial?.[f]??(f==='active'?true:f==='isCurrent'?false:''));setForm(x);setError('')},[initial,open,fields.join(',')]);
 const set=(k:string)=>(e:any)=>setForm((x:any)=>({...x,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 const save=async()=>{setSaving(true);try{if(initial)await api.put(`${endpoint}/${initial.id}`,form);else await api.post(endpoint,form);onSaved()}catch(e){setError(err(e))}finally{setSaving(false)}};
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{initial?'Edit':'Add'} record</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}{fields.map(f=>f==='active'||f==='isCurrent'?<Select key={f} value={String(form[f])} onChange={e=>setForm((x:any)=>({...x,[f]:e.target.value==='true'}))}><MenuItem value="true">Active / Current</MenuItem><MenuItem value="false">Inactive / Not current</MenuItem></Select>:<TextField key={f} label={f} value={form[f]??''} onChange={set(f)} type={f.toLowerCase().includes('date')?'date':'text'} slotProps={f.toLowerCase().includes('date')?{inputLabel:{shrink:true}}:undefined}/>)}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving?'Saving…':'Save'}</Button></DialogActions></Dialog>
}

function BatchDialog({open,initial,onClose,onSaved}:{open:boolean;initial:any;onClose:()=>void;onSaved:()=>void}){
 const {rows:years}=useList('/academic-years');
 const {rows:classes}=useList('/classes');
 const {rows:streams}=useList('/streams');
 const [form,setForm]=useState<any>({academicYearId:'',classId:'',streamId:'',name:'',code:'',capacity:'',status:'ACTIVE'});
 const [saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{
   const currentYear=years.find((x:any)=>x.isCurrent)?.id||years[0]?.id||'';
   setForm({
     academicYearId:initial?.academicYearId||initial?.academic_year_id||currentYear,
     classId:initial?.classId||initial?.class_id||'',
     streamId:initial?.streamId||initial?.stream_id||'',
     name:initial?.name||'', code:initial?.code||'', capacity:initial?.capacity??'', status:initial?.status||'ACTIVE'
   });
   setError('');
 },[open,initial,years]);
 const set=(key:string)=>(e:any)=>setForm((x:any)=>({...x,[key]:e.target.value}));
 const save=async()=>{
   if(!form.academicYearId||!form.classId||!form.name.trim()){setError('Academic year, class and batch name are required.');return;}
   setSaving(true);setError('');
   try{
     const payload={...form,streamId:form.streamId||null,capacity:form.capacity===''?null:Number(form.capacity)};
     if(initial) await api.put(`/batches/${initial.id}`,payload); else await api.post('/batches',payload);
     onSaved();
   }catch(e){setError(err(e))}finally{setSaving(false)}
 };
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
   <DialogTitle>{initial?'Edit':'Add'} batch</DialogTitle>
   <DialogContent><Stack spacing={2} mt={1}>
     {error&&<Alert severity="error">{error}</Alert>}
     <Select value={form.academicYearId} displayEmpty onChange={set('academicYearId')}><MenuItem value="" disabled>Select academic year</MenuItem>{years.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}{x.isCurrent?' • Current':''}</MenuItem>)}</Select>
     <Select value={form.classId} displayEmpty onChange={set('classId')}><MenuItem value="" disabled>Select class</MenuItem>{classes.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select>
     <Select value={form.streamId} displayEmpty onChange={set('streamId')}><MenuItem value="">No stream</MenuItem>{streams.map((x:any)=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select>
     <TextField label="Batch name" value={form.name} onChange={set('name')} required/>
     <TextField label="Code" value={form.code} onChange={set('code')}/>
     <TextField label="Capacity" type="number" value={form.capacity} onChange={set('capacity')}/>
     <Select value={form.status} onChange={set('status')}><MenuItem value="ACTIVE">ACTIVE</MenuItem><MenuItem value="INACTIVE">INACTIVE</MenuItem></Select>
   </Stack></DialogContent>
   <DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={saving} onClick={save}>{saving?'Saving…':'Save batch'}</Button></DialogActions>
 </Dialog>;
}

export function LiveAttendancePage(){
 const {rows:batches,loading:batchLoading}=useList('/batches');
 const {rows:subjects}=useList('/subjects');
 const [batchId,setBatchId]=useState(''); const [date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [sessions,setSessions]=useState<any[]>([]); const [session,setSession]=useState<any>(null); const [records,setRecords]=useState<any[]>([]); const [summary,setSummary]=useState<any>({});
 const [creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [creatingSubject,setCreatingSubject]=useState(''),[creatingStart,setCreatingStart]=useState(''),[creatingEnd,setCreatingEnd]=useState('');
 useEffect(()=>{if(!batchId&&batches[0]?.id)setBatchId(batches[0].id)},[batches,batchId]);
 const load=async()=>{if(!batchId)return;setError('');try{const list=unwrap(await api.get('/attendance/sessions',{params:{batchId,date}}))||[];setSessions(list);const current=session?.id?list.find((x:any)=>x.id===session.id):list[0];setSession(current||null);if(current){const [r,s]=await Promise.all([api.get('/attendance/sessions/'+current.id+'/records'),api.get('/attendance/sessions/'+current.id+'/summary')]);setRecords(unwrap(r)||[]);setSummary(unwrap(s)||{})}else{setRecords([]);setSummary({})}}catch(e){setError(err(e))}};
 useEffect(()=>{load()},[batchId,date]);
 const createSession=async()=>{setSaving(true);setError('');try{await api.post('/attendance/sessions',{batchId,subjectId:creatingSubject||null,sessionDate:date,startTime:creatingStart||null,endTime:creatingEnd||null});setCreating(false);setCreatingSubject('');setCreatingStart('');setCreatingEnd('');await load()}catch(e){setError(err(e))}finally{setSaving(false)}};
 const save=async()=>{if(!session)return;setSaving(true);setError('');try{await api.post('/attendance/sessions/'+session.id+'/records/bulk',{records:records.map(r=>({studentId:r.student_id,status:r.status}))});await load()}catch(e){setError(err(e))}finally{setSaving(false)}};
 const setAll=(status:string)=>setRecords(x=>x.map(r=>({...r,status})));
 const present=Number(summary.present||0),absent=Number(summary.absent||0),late=Number(summary.late||0),leave=Number(summary.leave||0),unmarked=Number(summary.unmarked||0),total=Number(summary.total||records.length);
 const percentage=total?Math.round(((present+late)/total)*100):0;
 return <Stack spacing={2.5}>
  <Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent><Stack direction={{xs:'column',lg:'row'}} gap={1.5} alignItems={{lg:'center'}}>
   <Select size="small" value={batchId} onChange={e=>{setBatchId(e.target.value as string);setSession(null)}} displayEmpty sx={{minWidth:240}}><MenuItem value="" disabled>{batchLoading?'Loading batches…':'Select batch'}</MenuItem>{batches.map(b=><MenuItem key={b.id} value={b.id}>{b.name}</MenuItem>)}</Select>
   <TextField size="small" type="date" value={date} onChange={e=>{setDate(e.target.value);setSession(null)}} slotProps={{inputLabel:{shrink:true}}}/>
   <Select size="small" value={session?.id||''} onChange={e=>setSession(sessions.find(x=>x.id===e.target.value)||null)} displayEmpty sx={{minWidth:260}}><MenuItem value="" disabled>{sessions.length?'Select session':'No sessions for this date'}</MenuItem>{sessions.map(s=><MenuItem key={s.id} value={s.id}>{s.subject_name}{s.start_time?' • '+s.start_time:''}</MenuItem>)}</Select>
   <Box flex={1}/><Button variant="outlined" onClick={()=>setCreating(true)} disabled={!batchId}>Create session</Button><Button variant="contained" onClick={save} disabled={!session||saving}>{saving?'Saving…':'Save attendance'}</Button>
  </Stack></CardContent></Card>
  {error&&<Alert severity="error">{error}</Alert>}
  {session&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'repeat(2,1fr)',md:'repeat(6,1fr)'},gap:1.5}}>{[['Total',total],['Present',present],['Absent',absent],['Late',late],['Leave',leave],['Attendance',percentage+'%']].map(([a,b])=><Stat key={String(a)} label={String(a)} value={b} icon={EventAvailableRounded}/>)}</Box>}
  {session&&<Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent>
   <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1} mb={1.5}><Box><Typography sx={{fontWeight:900}}>{session.batch_name} • {session.subject_name}</Typography><Typography sx={{fontSize:12,color:'text.secondary'}}>{date}{session.start_time?' • '+session.start_time:''}</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button size="small" variant="outlined" onClick={()=>setAll('PRESENT')}>Mark all present</Button><Button size="small" variant="outlined" onClick={()=>setAll('ABSENT')}>Mark all absent</Button></Stack></Stack>
   {unmarked>0&&<Alert severity="warning" sx={{mb:1.5}}>{unmarked} student(s) are still unmarked.</Alert>}
   {records.map((r,i)=><Stack key={r.student_id} direction="row" alignItems="center" gap={2} py={1.2} sx={{borderTop:'1px solid #f1f5f9'}}><Box flex={1}><Typography sx={{fontWeight:800}}>{r.first_name} {r.last_name||''}</Typography><Typography sx={{fontSize:11,color:'text.secondary'}}>{r.admission_number}</Typography></Box><Select size="small" value={r.status||'UNMARKED'} onChange={e=>setRecords(x=>x.map((z,j)=>j===i?{...z,status:e.target.value}:z))} sx={{minWidth:145}}>{['UNMARKED','PRESENT','ABSENT','LATE','LEAVE'].map(v=><MenuItem key={v} value={v}>{v==='UNMARKED'?'Not marked':v}</MenuItem>)}</Select></Stack>)}
   {!records.length&&<Typography color="text.secondary">No enrolled students in this batch.</Typography>}
  </CardContent></Card>}
  <Dialog open={creating} onClose={()=>setCreating(false)} fullWidth maxWidth="sm"><DialogTitle>Create attendance session</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Typography sx={{fontSize:12,color:'text.secondary'}}>Batch: {batches.find((b:any)=>b.id===batchId)?.name||'—'} • {date}</Typography><Select value={creatingSubject} displayEmpty onChange={e=>setCreatingSubject(e.target.value as string)}><MenuItem value="">General session</MenuItem>{subjects.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</Select><Box sx={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:2}}><TextField label="Start time" type="time" value={creatingStart} onChange={e=>setCreatingStart(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField label="End time" type="time" value={creatingEnd} onChange={e=>setCreatingEnd(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/></Box></Stack></DialogContent><DialogActions><Button onClick={()=>setCreating(false)}>Cancel</Button><Button variant="contained" onClick={createSession} disabled={saving}>Create session</Button></DialogActions></Dialog>
 </Stack>;
}
export function LiveFinancePage(){
 const {rows:invoices,loading,error,load}=useList('/finance/invoices');const {rows:students}=useList('/students');const [summary,setSummary]=useState<any>({});const [open,setOpen]=useState(false);const [pay,setPay]=useState<any>(null);
 const refresh=async()=>{load();try{setSummary(unwrap(await api.get('/finance/summary'))||{})}catch{}};useEffect(()=>{refresh()},[]);
 return <Stack spacing={2.5}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'},gap:2}}><Stat label="Invoices" value={summary.invoices??0} icon={PaymentsRounded}/><Stat label="Billed" value={money(summary.billed)} icon={PaymentsRounded}/><Stat label="Collected" value={money(summary.collected)} icon={PaymentsRounded}/><Stat label="Outstanding" value={money(summary.outstanding)} icon={PaymentsRounded}/></Box><Stack direction="row" justifyContent="flex-end"><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>setOpen(true)}>Create invoice</Button></Stack><Card elevation={0} sx={{border:'1px solid #e5e7eb'}}><CardContent sx={{p:0,overflow:'auto'}}><Busy loading={loading} error={error}/>{!loading&&!error&&<Table><TableHead><TableRow>{['Invoice','Student','Amount','Paid','Due','Status',''].map(x=><TableCell key={x} sx={{fontWeight:900,fontSize:11}}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{invoices.map(i=><TableRow key={i.id}><TableCell>{i.invoice_number}</TableCell><TableCell>{i.first_name?i.first_name+' '+(i.last_name||''):i.student_id}</TableCell><TableCell>{money(i.amount)}</TableCell><TableCell>{money(i.paid_amount)}</TableCell><TableCell>{i.due_date}</TableCell><TableCell><Chip size="small" label={i.status} color={i.status==='PAID'?'success':i.status==='PARTIALLY_PAID'?'warning':'default'} variant="outlined"/></TableCell><TableCell align="right">{i.status!=='PAID'&&<Button size="small" onClick={()=>setPay(i)}>Record payment</Button>}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card><InvoiceDialog open={open} students={students} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);refresh()}}/><PaymentDialog invoice={pay} onClose={()=>setPay(null)} onSaved={()=>{setPay(null);refresh()}}/></Stack>
}
function InvoiceDialog({open,students,onClose,onSaved}:{open:boolean;students:any[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({studentId:'',amount:'',dueDate:new Date().toISOString().slice(0,10),invoiceNumber:''});const [error,setError]=useState('');const save=async()=>{try{await api.post('/finance/invoices',{...f,amount:Number(f.amount),invoiceNumber:f.invoiceNumber||null,installmentId:null});onSaved()}catch(e){setError(err(e))}};return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Create invoice</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Select value={f.studentId} displayEmpty onChange={e=>setF((x:any)=>({...x,studentId:e.target.value}))}><MenuItem value="" disabled>Select student</MenuItem>{students.map(s=><MenuItem key={s.id} value={s.id}>{s.admissionNumber} • {s.firstName} {s.lastName||''}</MenuItem>)}</Select><TextField label="Amount" type="number" value={f.amount} onChange={e=>setF((x:any)=>({...x,amount:e.target.value}))}/><TextField label="Due date" type="date" value={f.dueDate} onChange={e=>setF((x:any)=>({...x,dueDate:e.target.value}))} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Invoice number (optional)" value={f.invoiceNumber} onChange={e=>setF((x:any)=>({...x,invoiceNumber:e.target.value}))}/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Create</Button></DialogActions></Dialog>}
function PaymentDialog({invoice,onClose,onSaved}:{invoice:any;onClose:()=>void;onSaved:()=>void}){const [amount,setAmount]=useState('');const [error,setError]=useState('');useEffect(()=>{if(invoice)setAmount(String(Number(invoice.amount)-Number(invoice.paid_amount||0)))},[invoice]);const save=async()=>{try{await api.post('/finance/payments',{invoiceId:invoice.id,amount:Number(amount),gateway:'MANUAL',idempotencyKey:`manual-${invoice.id}-${amount}`});onSaved()}catch(e){setError(err(e))}};return <Dialog open={!!invoice} onClose={onClose}><DialogTitle>Record payment</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Typography>Balance: <b>{money(Number(invoice?.amount||0)-Number(invoice?.paid_amount||0))}</b></Typography><TextField label="Payment amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Confirm payment</Button></DialogActions></Dialog>}
