import { useState } from 'react';
import { Box, Button, Card, CardContent, Chip, Divider, IconButton, LinearProgress, MenuItem, Paper, Select, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { ArrowForwardRounded, CheckCircleRounded, EventAvailableRounded, MenuBookRounded, NotificationsRounded, PaymentsRounded, QuizRounded, VideoCallRounded, WarningAmberRounded } from '@mui/icons-material';

const border = '#e5e7eb';

export function StudentPortal() {
  const [tab, setTab] = useState(0);
  return <Stack spacing={2.5}>
    <Card elevation={0} sx={{ border: `1px solid ${border}`, borderRadius: 3, background: 'linear-gradient(135deg,#ffffff 60%,#ecfdf5)' }}>
      <CardContent sx={{ p: { xs: 2, md: 3 } }}><Stack direction={{ xs: 'column', md: 'row' }} gap={2} alignItems={{ md: 'center' }}><Box sx={{ width: 60, height: 60, borderRadius: 3, bgcolor: '#dff7f2', color: '#0f766e', display: 'grid', placeItems: 'center', fontWeight: 900, fontSize: 21 }}>AS</Box><Box flex={1}><Typography fontSize={12} color="text.secondary">Student portal</Typography><Typography fontSize={25} fontWeight={900}>Aarav Sharma</Typography><Typography fontSize={12} color="text.secondary">Class 12-A • PCM • Roll 24</Typography></Box><Chip label="Attendance 92%" color="success" variant="outlined"/><Button variant="outlined" startIcon={<VideoCallRounded />}>Join class</Button></Stack></CardContent>
    </Card>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr 1fr', md: 'repeat(4,1fr)' }, gap: 2 }}>{[['Attendance','92%','Above target',EventAvailableRounded],['Average','84.6%','+5.8%',QuizRounded],['Assignments','4','Due this week',MenuBookRounded],['Fees','₹18,000','Due 10 Oct',PaymentsRounded]].map(([a,b,c,I]) => {const Icon=I as any; return <Card key={a as string} elevation={0} sx={{ border: `1px solid ${border}` }}><CardContent><Icon sx={{ color:'#0f766e', fontSize:20 }}/><Typography fontSize={12} color="text.secondary" mt={1}>{a as string}</Typography><Typography fontSize={24} fontWeight={900}>{b as string}</Typography><Typography fontSize={11} color="text.secondary">{c as string}</Typography></CardContent></Card>})}</Box>
    <Card elevation={0} sx={{ border: `1px solid ${border}` }}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Overview"/><Tab label="Attendance"/><Tab label="Homework"/><Tab label="Results"/><Tab label="Fees"/></Tabs><Divider/><CardContent>{tab===0&&<Overview/>}{tab===1&&<AttendanceHistory/>}{tab===2&&<Homework/>}{tab===3&&<Results/>}{tab===4&&<Fees/>}</CardContent></Card>
  </Stack>;
}
function Overview(){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1.2fr .8fr'},gap:2}}><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={900} mb={2}>Upcoming today</Typography>{[['09:00','Physics','Room 204'],['10:30','Mathematics','Room 108'],['14:00','Chemistry','Lab 2']].map(x=><Stack key={x[0]} direction="row" gap={2} py={1.2} sx={{borderBottom:`1px solid #f1f5f9`}}><Typography fontWeight={900} fontSize={12} sx={{width:48}}>{x[0]}</Typography><Box flex={1}><Typography fontSize={13} fontWeight={700}>{x[1]}</Typography><Typography fontSize={11} color="text.secondary">{x[2]}</Typography></Box><Button size="small">Open</Button></Stack>)}</Paper><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={900} mb={2}>Focus areas</Typography>{[['Mathematics','79%'],['Chemistry','84%'],['Physics','91%']].map(x=><Box key={x[0]} mb={1.8}><Stack direction="row" justifyContent="space-between"><Typography fontSize={12} fontWeight={700}>{x[0]}</Typography><Typography fontSize={11}>{x[1]}</Typography></Stack><LinearProgress variant="determinate" value={parseInt(x[1])} sx={{mt:.7,height:7,borderRadius:5}}/></Box>)}</Paper></Box>}
function AttendanceHistory(){return <Stack spacing={1.2}>{['Mon 28 Sep','Tue 29 Sep','Wed 30 Sep','Thu 01 Oct','Fri 02 Oct'].map((d,i)=><Stack key={d} direction="row" alignItems="center" gap={2} p={1.4} sx={{border:'1px solid #eef2f7',borderRadius:2}}><EventAvailableRounded sx={{color:'#0f766e'}}/><Box flex={1}><Typography fontSize={13} fontWeight={800}>{d}</Typography><Typography fontSize={11} color="text.secondary">All scheduled classes</Typography></Box><Chip size="small" label={i===2?'Late':'Present'} color={i===2?'warning':'success'} variant="outlined"/></Stack>)}</Stack>}
function Homework(){return <Stack spacing={1.2}>{[['Physics assignment','Due today','3 questions'],['Maths practice set','Due 07 Oct','20 questions'],['Chemistry notes','Submitted','PDF upload']].map(x=><Paper key={x[0]} variant="outlined" sx={{p:1.6}}><Stack direction="row" gap={2} alignItems="center"><MenuBookRounded sx={{color:'#0f766e'}}/><Box flex={1}><Typography fontSize={13} fontWeight={800}>{x[0]}</Typography><Typography fontSize={11} color="text.secondary">{x[2]}</Typography></Box><Chip size="small" label={x[1]} variant="outlined"/><Button size="small" endIcon={<ArrowForwardRounded/>}>Open</Button></Stack></Paper>)}</Stack>}
function Results(){return <Stack spacing={1.2}>{[['Unit Test 3','84.6%','Rank 7'],['Weekly Test 14','91.2%','Rank 4'],['Physics Unit 2','88%','Rank 5']].map(x=><Paper key={x[0]} variant="outlined" sx={{p:1.6}}><Stack direction="row" alignItems="center"><Box flex={1}><Typography fontSize={13} fontWeight={800}>{x[0]}</Typography><Typography fontSize={11} color="text.secondary">Published • detailed analysis available</Typography></Box><Typography fontSize={20} fontWeight={900} mr={2}>{x[1]}</Typography><Chip size="small" label={x[2]}/></Stack></Paper>)}</Stack>}
function Fees(){return <Stack spacing={1.2}><Paper variant="outlined" sx={{p:2}}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={900}>Outstanding balance</Typography><Typography fontSize={11} color="text.secondary">Invoice INV-2026-1024 • Due 10 Oct</Typography></Box><Typography fontSize={22} fontWeight={900}>₹18,000</Typography></Stack><Button fullWidth variant="contained" sx={{mt:2}}>Pay now</Button></Paper><Paper variant="outlined" sx={{p:2}}><Typography fontWeight={900}>Payment history</Typography><Typography fontSize={11} color="text.secondary" mt={.5}>Last payment ₹12,500 • 01 Sep 2026</Typography></Paper></Stack>}

export function ParentPortal(){return <Stack spacing={2.5}><Card elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Stack direction={{xs:'column',sm:'row'}} gap={2} alignItems={{sm:'center'}}><Box flex={1}><Typography fontSize={12} color="text.secondary">Parent portal</Typography><Typography fontSize={25} fontWeight={900}>Good morning, Priya</Typography><Typography fontSize={12} color="text.secondary">2 children linked to this account</Typography></Box><Button variant="outlined" startIcon={<NotificationsRounded/>}>Notifications <Chip size="small" label="4" sx={{ml:1}}/></Button></Stack></CardContent></Card><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}>{['Aarav Sharma','Ananya Sharma'].map((n,i)=><Card key={n} elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Stack direction="row" alignItems="center" gap={2}><Box sx={{width:48,height:48,borderRadius:2.5,bgcolor:'#e8f8f5',display:'grid',placeItems:'center',fontWeight:900,color:'#0f766e'}}>{i?'AS':'AS'}</Box><Box flex={1}><Typography fontWeight={900}>{n}</Typography><Typography fontSize={11} color="text.secondary">{i?'10-A':'12-A'} • Attendance {i?'89':'92'}%</Typography></Box><Chip size="small" label={i?'On track':'Needs attention'} color={i?'success':'warning'} variant="outlined"/></Stack><Divider sx={{my:2}}/><Stack direction="row" justifyContent="space-between"><Typography fontSize={12}>Fee due</Typography><Typography fontSize={12} fontWeight={900}>{i?'₹8,500':'₹18,000'}</Typography></Stack><Button fullWidth sx={{mt:1.5}} variant="outlined">View child dashboard</Button></CardContent></Card>)}</Box><Card elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Typography fontWeight={900} mb={1.5}>Important updates</Typography>{['Aarav has a Mathematics test tomorrow at 10:30 AM.','Fee reminder: Aarav’s installment is due on 10 Oct.','Parent-teacher meeting scheduled for Friday.'].map(x=><Stack key={x} direction="row" gap={1.2} py={1.2} sx={{borderTop:`1px solid #f1f5f9`}}><WarningAmberRounded sx={{fontSize:18,color:'#d97706'}}/><Typography fontSize={12}>{x}</Typography></Stack>)}</CardContent></Card></Stack>}

export function TeacherPortal(){return <Stack spacing={2.5}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'},gap:2}}>{[['My batches','6','Assigned'],['Today classes','5','2 completed'],['Pending reviews','28','Needs action'],['Attendance','94.2%','This month']].map(x=><Card key={x[0]} elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Typography fontSize={12} color="text.secondary">{x[0]}</Typography><Typography fontSize={25} fontWeight={900}>{x[1]}</Typography><Typography fontSize={11} color="text.secondary">{x[2]}</Typography></CardContent></Card>)}</Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.25fr .75fr'},gap:2}}><Card elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Stack direction="row" justifyContent="space-between" mb={2}><Typography fontWeight={900}>Today’s classes</Typography><Button variant="contained" size="small">Mark attendance</Button></Stack>{[['09:00','12-A • Physics','42 students'],['10:30','11-B • Physics','36 students'],['14:00','12-C • Physics','39 students']].map(x=><Paper key={x[0]} variant="outlined" sx={{p:1.5,mb:1.2}}><Stack direction="row" alignItems="center" gap={2}><Typography fontWeight={900} fontSize={12} sx={{width:50}}>{x[0]}</Typography><Box flex={1}><Typography fontSize={13} fontWeight={800}>{x[1]}</Typography><Typography fontSize={11} color="text.secondary">{x[2]}</Typography></Box><Button size="small">Open</Button></Stack></Paper>)}</CardContent></Card><Card elevation={0} sx={{border:`1px solid ${border}`}}><CardContent><Typography fontWeight={900}>To review</Typography>{['8 assignments','12 exam answers','3 parent messages'].map(x=><Stack key={x} direction="row" alignItems="center" py={1.4} gap={1.2}><CheckCircleRounded sx={{color:'#0f766e',fontSize:18}}/><Typography fontSize={12} flex={1}>{x}</Typography><IconButton size="small"><ArrowForwardRounded fontSize="small"/></IconButton></Stack>)}</CardContent></Card></Box></Stack>}

export function SettingsPage(){const [tab,setTab]=useState(0);return <Stack spacing={2.5}><Card elevation={0} sx={{border:`1px solid ${border}`}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Institute"/><Tab label="Academic"/><Tab label="Policies"/><Tab label="Notifications"/><Tab label="Integrations"/><Tab label="Users & Roles"/></Tabs><Divider/><CardContent>{tab===0&&<SettingsInstitute/>}{tab===1&&<SettingsAcademic/>}{tab===2&&<SettingsPolicies/>}{tab===3&&<SettingsNotifications/>}{tab===4&&<SettingsIntegrations/>}{tab===5&&<SettingsUsers/>}</CardContent></Card></Stack>}
function SettingsInstitute(){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}>{[['Institute name','Bright Future Academy'],['Contact email','admin@brightfuture.edu'],['Phone','+91 98765 43210'],['Timezone','Asia/Kolkata']].map(x=><TextField key={x[0]} label={x[0]} defaultValue={x[1]} fullWidth size="small"/>)}<TextField label="Primary color" defaultValue="#0F766E" fullWidth size="small"/><TextField label="Address" defaultValue="Nagpur, Maharashtra" fullWidth size="small"/><Box sx={{gridColumn:{md:'1 / -1'}}}><Button variant="contained">Save changes</Button></Box></Box>}
function SettingsAcademic(){return <Stack spacing={2}><Typography fontWeight={900}>Academic configuration</Typography><Stack direction={{xs:'column',sm:'row'}} gap={2}><Select size="small" defaultValue="2026-27" sx={{minWidth:180}}><MenuItem value="2026-27">2026–27</MenuItem></Select><Select size="small" defaultValue="5-12" sx={{minWidth:180}}><MenuItem value="5-12">Classes 5th–12th</MenuItem></Select></Stack><Typography fontSize={12} color="text.secondary">Streams, subjects and batches are configured independently per academic year.</Typography></Stack>}
function SettingsPolicies(){return <Stack spacing={1.5}>{[['Fee-based attendance restriction','Prevent student self check-in when eligible invoices are overdue',true],['Public ranking','Allow institute to expose rankings to students and parents',false],['Parent messaging','Allow teachers to message linked parents',true],['Video recording','Allow recording where provider and consent policy permit',false]].map(([a,b,v])=><Paper key={a as string} variant="outlined" sx={{p:1.7}}><Stack direction="row" alignItems="center" gap={2}><Box flex={1}><Typography fontSize={13} fontWeight={800}>{a as string}</Typography><Typography fontSize={11} color="text.secondary">{b as string}</Typography></Box><Chip label={v?'Enabled':'Disabled'} color={v?'success':'default'} variant="outlined"/></Stack></Paper>)}<Button variant="contained" sx={{alignSelf:'flex-start'}}>Save policy settings</Button></Stack>}
function SettingsNotifications(){return <Stack spacing={1.3}>{['Attendance alerts','Fee reminders','Exam/result alerts','Announcements','Ticket escalations'].map(x=><Stack key={x} direction="row" alignItems="center" gap={2} p={1.5} border={`1px solid #eef2f7`} borderRadius={2}><Box flex={1}><Typography fontSize={13} fontWeight={800}>{x}</Typography><Typography fontSize={11} color="text.secondary">In-app • Push • Email</Typography></Box><Chip size="small" label="Configured" color="success" variant="outlined"/></Stack>)}</Stack>}
function SettingsIntegrations(){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:1.5}}>{['Razorpay','Email provider','WhatsApp','Video provider','S3 / Object Storage','RabbitMQ'].map(x=><Paper key={x} variant="outlined" sx={{p:1.8}}><Stack direction="row" alignItems="center"><Box flex={1}><Typography fontWeight={800} fontSize={13}>{x}</Typography><Typography fontSize={11} color="text.secondary">Provider abstraction ready</Typography></Box><Chip size="small" label={x==='RabbitMQ'?'Connected':'Not configured'} color={x==='RabbitMQ'?'success':'default'} variant="outlined"/></Stack></Paper>)}</Box>}
function SettingsUsers(){return <Stack spacing={1.2}>{[['Institute Owner','1','Full access'],['Institute Admin','2','Configurable'],['Teacher','42','Assigned batches'],['Student','1,248','Own data'],['Parent','986','Linked children'],['Support','4','Tickets & communication']].map(x=><Paper key={x[0]} variant="outlined" sx={{p:1.5}}><Stack direction="row"><Box flex={1}><Typography fontSize={13} fontWeight={800}>{x[0]}</Typography><Typography fontSize={11} color="text.secondary">{x[2]}</Typography></Box><Typography fontWeight={900}>{x[1]}</Typography><Button size="small">Manage</Button></Stack></Paper>)}</Stack>}
