import {useEffect,useState} from 'react';
import {Alert,Box,Card,CardContent,Chip,Divider,MenuItem,Select,Stack,Table,TableBody,TableCell,TableHead,TableRow,Typography} from '@mui/material';
import {EventAvailableRounded,PaymentsRounded,SchoolRounded,AssignmentRounded} from '@mui/icons-material';
import {api} from '../services';
function unwrap(r:any){return r?.data?.data??r?.data??[]}
const money=(n:any)=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
export default function PortalPage(){
 const [children,setChildren]=useState<any[]>([]),[id,setId]=useState(''),[data,setData]=useState<any>(),[error,setError]=useState('');
 async function load(){try{const r=await api.get('/portal/me');const d=unwrap(r);setChildren(d.children||[]);if(!id&&d.children?.[0]?.id)setId(d.children[0].id)}catch(e:any){setError(e?.response?.data?.message||'Unable to load portal')}}
 async function loadStudent(sid=id){if(!sid)return;try{setData(unwrap(await api.get('/portal/student/'+sid)))}catch(e:any){setError(e?.response?.data?.message||'Unable to load student portal')}}
 useEffect(()=>{load()},[]);useEffect(()=>{loadStudent()},[id]);
 if(error)return <Alert severity="error">{error}</Alert>;
 if(!children.length)return <Card variant="outlined"><CardContent sx={{py:8,textAlign:'center'}}><Typography sx={{fontWeight:900}}>No linked student profile</Typography><Typography sx={{color:'#64748b',fontSize:13}}>Your institute has not linked a student to this portal account yet.</Typography></CardContent></Card>;
 return <Stack spacing={2.5}><Stack direction={{xs:'column',sm:'row'}} sx={{justifyContent:'space-between',alignItems:{sm:'center'}}} spacing={1}><Box><Typography sx={{fontSize:12,color:'#64748b'}}>My Portal</Typography><Typography variant="h5" sx={{fontWeight:900}}>Student / Parent Workspace</Typography></Box><Select size="small" value={id} onChange={e=>setId(e.target.value)}>{children.map(c=><MenuItem key={c.id} value={c.id}>{c.first_name} {c.last_name||''}</MenuItem>)}</Select></Stack>
 {data&&<><Card variant="outlined" sx={{borderRadius:3}}><CardContent><Stack direction="row" spacing={2} sx={{alignItems:"center"}}><Box sx={{width:48,height:48,borderRadius:2,bgcolor:'#e8f8f5',display:'grid',placeItems:'center'}}><SchoolRounded color="success"/></Box><Box><Typography sx={{fontWeight:900}}>{data.student.first_name} {data.student.last_name||''}</Typography><Typography sx={{fontSize:12,color:'#64748b'}}>{data.student.admission_number} · {data.student.status}</Typography></Box></Stack></CardContent></Card>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(4,1fr)'},gap:2}}><Stat icon={EventAvailableRounded} label="Attendance" value={(data.attendance||[]).reduce((a:any,x:any)=>a+Number(x.total||0),0)+' records'}/><Stat icon={PaymentsRounded} label="Invoices" value={(data.fees||[]).length}/><Stat icon={SchoolRounded} label="Published Results" value={(data.results||[]).length}/><Stat icon={AssignmentRounded} label="Homework" value={(data.homework||[]).length}/></Box>
 <Card variant="outlined"><CardContent><Typography sx={{fontWeight:900,mb:1}}>Fees</Typography><Table size="small"><TableHead><TableRow><TableCell>Invoice</TableCell><TableCell>Due</TableCell><TableCell>Amount</TableCell><TableCell>Paid</TableCell><TableCell>Status</TableCell></TableRow></TableHead><TableBody>{(data.fees||[]).map((x:any)=><TableRow key={x.invoice_number}><TableCell>{x.invoice_number}</TableCell><TableCell>{x.due_date}</TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{money(x.paid_amount)}</TableCell><TableCell><Chip size="small" label={x.status}/></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
 <Card variant="outlined"><CardContent><Typography sx={{fontWeight:900,mb:1}}>Results</Typography>{!(data.results||[]).length?<Typography sx={{color:'#64748b',fontSize:13}}>No published results yet.</Typography>:data.results.map((x:any)=><Box key={x.id} sx={{p:1.5,borderBottom:'1px solid #eef2f7'}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography sx={{fontWeight:800}}>{x.exam_name}</Typography><Typography sx={{fontWeight:900}}>{x.percentage??0}%</Typography></Stack><Typography sx={{fontSize:12,color:'#64748b'}}>Rank: {x.rank??'—'} · {x.obtained_marks??0}/{x.total_marks??0}</Typography></Box>)}</CardContent></Card>
 <Card variant="outlined"><CardContent><Typography sx={{fontWeight:900,mb:1}}>Homework</Typography>{!(data.homework||[]).length?<Typography sx={{color:'#64748b',fontSize:13}}>No homework assigned.</Typography>:data.homework.map((x:any)=><Box key={x.id} sx={{p:1.5,borderBottom:'1px solid #eef2f7'}}><Typography sx={{fontWeight:800}}>{x.title}</Typography><Typography sx={{fontSize:12,color:'#64748b'}}>{x.due_at?new Date(x.due_at).toLocaleString():'No due date'}</Typography></Box>)}</CardContent></Card>
 </>}</Stack>
}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <Card variant="outlined" sx={{borderRadius:3}}><CardContent><Icon sx={{fontSize:20,color:'#0f766e'}}/><Typography sx={{fontSize:11,color:'#64748b',mt:1}}>{label}</Typography><Typography sx={{fontSize:22,fontWeight:900}}>{value}</Typography></CardContent></Card>}
