import {useEffect,useState} from 'react';
import {api} from '../services';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Select,Stack,Tab,Tabs,TextField,Typography} from '@mui/material';
import {AddRounded,DeleteOutlineRounded,AutoAwesomeRounded,LayersRounded,RefreshRounded} from '@mui/icons-material';
const unwrap=(r:any)=>r?.data?.data??r?.data;
const msg=(e:any)=>e?.response?.data?.message??e?.response?.data?.error?.message??e?.message??'Request failed';
function useLive(path:string){const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);setError('');try{const d=unwrap(await api.get(path));setRows(Array.isArray(d)?d:[])}catch(e){setError(msg(e))}finally{setLoading(false)}};useEffect(()=>{load()},[path]);return{rows,loading,error,load}}
export default function ProgramConfigurationPage(){
 const programs=useLive('/programs'),templates=useLive('/programs/templates'),subjects=useLive('/subjects');const[tab,setTab]=useState(0);const[open,setOpen]=useState(false);const[edit,setEdit]=useState<any>(null);
 return <Stack spacing={2.5}>
  <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Box><Typography sx={{fontSize:12,color:'#64748b',fontWeight:900}}>PROGRAM & EXAM CONFIGURATION</Typography><Typography sx={{fontSize:13,color:'#94a3b8',mt:.3}}>Configure what the institute teaches without changing the product code.</Typography></Box><Button variant="outlined" startIcon={<RefreshRounded/>} onClick={()=>{programs.load();templates.load()}}>Refresh</Button></Stack>
  <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(3,1fr)'},gap:1.5}}>
   {([
    ['Programs',programs.rows.length,LayersRounded],
    ['System exam templates',templates.rows.filter(x=>x.system_template).length,AutoAwesomeRounded],
    ['Active subjects',subjects.rows.filter(x=>x.active!==false).length,LayersRounded]
  ] as const).map(([l,v,Icon])=><Card key={l}><CardContent><Stack direction="row" spacing={1.5} alignItems="center"><Box sx={{width:40,height:40,borderRadius:2.5,bgcolor:'#e8f8f5',color:'#0f766e',display:'grid',placeItems:'center'}}><Icon fontSize="small"/></Box><Box><Typography sx={{fontSize:11,color:'#64748b'}}>{l}</Typography><Typography sx={{fontSize:25,fontWeight:950}}>{v}</Typography></Box></Stack></CardContent></Card>)}
  </Box>
  <Card><CardContent sx={{p:{xs:1,md:1.5}}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab label="Programs"/><Tab label="Exam Template Library"/></Tabs></CardContent></Card>
  {tab===0&&<Card><CardContent sx={{p:0}}><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{p:2}}><Box><Typography fontWeight={900}>Institute programs</Typography><Typography fontSize={11} color="text.secondary">Examples: Class 10 Foundation, JEE Main + Advanced, NEET, UPSC, Banking.</Typography></Box><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>{setEdit(null);setOpen(true)}}>Add program</Button></Stack>{programs.error&&<Alert severity="error" sx={{m:2}}>{programs.error}</Alert>}<Box sx={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Program','Code','Category','Level','Status',''].map(x=><th key={x} style={{padding:'11px 14px',textAlign:'left',fontSize:10,color:'#64748b'}}>{x}</th>)}</tr></thead><tbody>{programs.rows.map(r=><tr key={r.id}>{[r.name,r.code||'—',r.category,r.level||'—',r.active?'ACTIVE':'INACTIVE'].map((x:any,i)=><td key={i} style={{padding:'12px 14px',fontSize:12,borderTop:'1px solid #f1f5f9'}}>{i===4?<Chip size="small" label={x} variant="outlined"/>:x}</td>)}<td style={{padding:8,textAlign:'right',borderTop:'1px solid #f1f5f9'}}><Button size="small" onClick={()=>{setEdit(r);setOpen(true)}}>Edit</Button><Button size="small" color="error" startIcon={<DeleteOutlineRounded/>} onClick={async()=>{if(confirm('Delete this program?')){try{await api.delete('/programs/'+r.id);programs.load()}catch(e){alert(msg(e))}}}}>Delete</Button></td></tr>)}{!programs.rows.length&&<tr><td colSpan={6} style={{padding:32,textAlign:'center',color:'#94a3b8'}}>No programs configured yet.</td></tr>}</tbody></table></Box></CardContent><ProgramDialog open={open} initial={edit} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);programs.load()}}/></Card>}
  {tab===1&&<TemplateLibrary templates={templates.rows}/>}
 </Stack>
}
function ProgramDialog({open,initial,onClose,onSaved}:any){const[f,setF]=useState<any>({name:'',code:'',category:'GENERAL',level:'',description:'',active:true}),[error,setError]=useState('');useEffect(()=>{setF({name:initial?.name||'',code:initial?.code||'',category:initial?.category||'GENERAL',level:initial?.level||'',description:initial?.description||'',active:initial?.active??true});setError('')},[open,initial]);const set=(k:string)=>(e:any)=>setF((x:any)=>({...x,[k]:e.target.value}));const save=async()=>{try{await(initial?api.put('/programs/'+initial.id,f):api.post('/programs',f));onSaved()}catch(e){setError(msg(e))}};return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{initial?'Edit':'Create'} program</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Program name" value={f.name} onChange={set('name')} required/><TextField label="Code" value={f.code} onChange={set('code')}/><Select value={f.category} onChange={set('category')}><MenuItem value="GENERAL">GENERAL</MenuItem><MenuItem value="SCHOOL">SCHOOL</MenuItem><MenuItem value="ENGINEERING">ENGINEERING</MenuItem><MenuItem value="MEDICAL">MEDICAL</MenuItem><MenuItem value="CIVIL_SERVICES">CIVIL SERVICES</MenuItem><MenuItem value="GOVERNMENT">GOVERNMENT</MenuItem><MenuItem value="MANAGEMENT">MANAGEMENT</MenuItem><MenuItem value="LAW">LAW</MenuItem><MenuItem value="DEFENCE">DEFENCE</MenuItem><MenuItem value="UNIVERSITY_ENTRANCE">UNIVERSITY ENTRANCE</MenuItem></Select><TextField label="Level / stage" value={f.level} onChange={set('level')} placeholder="e.g. Class 11–12, Prelims + Mains"/><TextField label="Description" multiline minRows={3} value={f.description} onChange={set('description')}/><Select value={String(f.active)} onChange={e=>setF((x:any)=>({...x,active:e.target.value==='true'}))}><MenuItem value="true">ACTIVE</MenuItem><MenuItem value="false">INACTIVE</MenuItem></Select></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={save}>Save program</Button></DialogActions></Dialog>}
function TemplateLibrary({templates}:any){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:1.75}}>{templates.map((t:any)=><Card key={t.id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={900}>{t.name}</Typography><Typography sx={{fontSize:11,color:'#64748b',mt:.3}}>{t.code} • {t.category}</Typography></Box><Chip size="small" label="SYSTEM TEMPLATE" variant="outlined"/></Stack><Typography sx={{fontSize:12,color:'#64748b',mt:1.5}}>{t.description}</Typography><Box sx={{mt:1.5,p:1.5,bgcolor:'#f8fafc',borderRadius:2,fontFamily:'monospace',fontSize:10,whiteSpace:'pre-wrap',overflow:'hidden'}}>{JSON.stringify(t.config,null,2)}</Box><Typography sx={{fontSize:10,color:'#94a3b8',mt:1}}>Use this as the starting configuration for an institute program; institute-specific values remain configurable.</Typography></CardContent></Card>)}{!templates.length&&<Alert severity="info">No exam templates available.</Alert>}</Box>}
